name: company_wiki
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_social_button: ^1.1.6+1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  toastification: ^3.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:


  uses-material-design: true

  assets:
    - assets/images/blurred_city.png
    - assets/images/defaultLogo.png
